#preload = /home/kieran/Pictures/Walls/aurora-northern-lights-4k-hh.jpg
#wallpaper = , /home/kieran/Pictures/Walls/aurora-northern-lights-4k-hh.jpg
preload = /home/kieran/Pictures/Walls/dust-4k.jpg
wallpaper = , /home/kieran/Pictures/Walls/dust-4k.jpg
