# Hyprland configuration
# https://wiki.hypr.land/Configuring/

# Source modular configuration files
source = ~/.config/hypr/colours.conf
source = ~/.config/hypr/vars.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/rules.conf
