general {
    lock_cmd =
    before_sleep_cmd =
    after_sleep_cmd =
}

listener {
    timeout = 300
    on-timeout = ddcutil --display 2 getvcp 10 -t | awk '{print $4}' > /tmp/oled-brightness && ddcutil --display 2 setvcp 10 5
    on-resume = ddcutil --display 2 setvcp 10 $(cat /tmp/oled-brightness)
}
