monitorv2 {
  output = DP-3
  mode = 3840x2160@240.0
  position = 0x0
  scale = 2
  transform = 0
  bitdepth = 10
  #cm = hdr
}

monitorv2 {
  output = HDMI-A-1
  mode = 3840x2160@60.0
  position = 1920x0
  scale = 2.5
}

xwayland {
  force_zero_scaling = true
}
