##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Slack always on workspace 10 (HDMI monitor)
windowrule {
    name = slack-to-hdmi
    match:class = ^(Slack)$

    workspace = 10
}

# Vivaldi on workspace 2
windowrule {
    name = vivaldi-ws2
    match:class = ^(vivaldi-stable)$

    workspace = 2
}

# Mailspring on workspace 9
windowrule {
    name = mailspring-ws9
    match:class = ^(Mailspring)$

    workspace = 9
}

# Steam on workspace 9
windowrule {
    name = steam-ws9
    match:class = ^(steam)$

    workspace = 9
}

# Discord on workspace 10
windowrule {
    name = discord-ws10
    match:class = ^(discord)$

    workspace = 10
}
